on: 
  push:
    branches:
      - v1.9_RC

jobs:
  doc_build_job:
    runs-on: ubuntu-latest
    # This project MUST be given permission to use the image blow. at
    # Package settings-> Manage action access of the project hosting the
    # package
    container: 'ghcr.io/thesystemdevelopmentkit/thesdktestimage:latest'
    name: Test the submodules and Update the thesdk_template
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test and update
        run: ./CI-helpers/test_and_release.sh -c -b "v1.9_RC" -t ${{ secrets.THESYDEKICK_TOKEN }}

## This is an example how to run a image pull if needed.
#  image_pull:
#    runs-on: ubuntu-latest
#    name: Pull docker image
#    steps:
#      - name: Login to Github Packages
#        uses: docker/login-action@v1
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN}}
#
#      - name: Pull image
#        uses: docker/login-action@v1
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN}}
#      - name: Pull Docker image
#        run: docker pull 'ghcr.io/thesystemdevelopmentkit/thesdktestimage:latest'

